const data = {
    products: [
        {
            name: 'Litto BlinkersClub Hoodie',
            slug: 'Litto-BlinkersClub-Hoodie',
            category: 'Shirts',
            image: '/images/Litto-BlinkersClub-Hoodie.webp',
            price: 70,
            brand: 'Litto',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Litto Merch',
            isFeatured: true,
            banner: '/images/banner1.jpg',
        },
        {
            name: 'Litto BlinkersClub Hoodie',
            slug: 'Litto-BlinkersClub-Hoodie',
            category: 'Shirts',
            image: '/images/Litto-BlinkersClub-Hoodie.webp',
            price: 70,
            brand: 'Litto',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Litto Merch',
            isFeatured: true,
            banner: '/images/banner1.jpg',
        },
        {
            name: 'Litto BlinkersClub Hoodie',
            slug: 'Litto-BlinkersClub-Hoodie',
            category: 'Shirts',
            image: '/images/Litto-BlinkersClub-Hoodie.webp',
            price: 70,
            brand: 'Litto',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Litto Merch',
            isFeatured: true,
            banner: '/images/banner1.jpg',
        },
        {
            name: 'Litto BlinkersClub Hoodie',
            slug: 'Litto-BlinkersClub-Hoodie',
            category: 'Shirts',
            image: '/images/Litto-BlinkersClub-Hoodie.webp',
            price: 70,
            brand: 'Litto',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Litto Merch',
            isFeatured: true,
            banner: '/images/banner1.jpg',
        },
        {
            name: 'Litto BlinkersClub Hoodie',
            slug: 'Litto-BlinkersClub-Hoodie',
            category: 'Shirts',
            image: '/images/Litto-BlinkersClub-Hoodie.webp',
            price: 70,
            brand: 'Litto',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Litto Merch',
            isFeatured: true,
            banner: '/images/banner1.jpg',
        },
        {
            name: 'Litto BlinkersClub Hoodie',
            slug: 'Litto-BlinkersClub-Hoodie',
            category: 'Shirts',
            image: '/images/Litto-BlinkersClub-Hoodie.webp',
            price: 70,
            brand: 'Litto',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Litto Merch',
            isFeatured: true,
            banner: '/images/banner1.jpg',
        },
    ]
}

export default data